// regex generated by chatgpt with this conversation
// https://chatgpt.com/share/6764b943-4e30-8011-9e10-334f781b5ff8

// Reflection mappings for pronouns and similar words.
const reflections = {
    "I": "you",
    "me": "you",
    "my": "your",
    "am": "are",
    "you": "I",
    "your": "my",
    "yours": "mine",
    "are": "am"
};

// A dictionary of responses based on various patterns.
const responses = {
    "hello|hi|hey": [
        "Hello! How are you feeling today?",
        "Hi there! What’s on your mind?",
        "Hey! How can I help you?"
    ],
    "you remind me of (.*)": [
        "Why do you think I remind you of $1?",
        "What makes you think of $1 when talking to me?",
        "Is it a good feeling to be reminded of $1?"
    ],
    "mother|father|family|parent": [
        "Tell me more about your family.",
        "How does that make you feel about your family?",
        "What role does your family play in your thoughts?"
    ],
    "I need(.*)": [
        "Why do you need $1?",
        "Would getting $1 really help you?",
        "What if you didn’t need $1?"
    ],
    "I am(.*)": [
        "Why do you think you are $1?",
        "How long have you felt that way?",
        "What made you feel like $1?"
    ],
    "I feel(.*)": [
        "Why do you feel $1?",
        "Does feeling $1 happen often?",
        "How does that feeling affect you?"
    ],
    "sorry|apologies": [
        "No need to apologize.",
        "Apologies aren't necessary. Why do you feel that way?",
        "It’s okay to feel that way."
    ],
    "bye|goodbye|exit": [
        "Goodbye! Take care.",
        "Thank you for sharing. Goodbye!",
        "Bye! I’m here if you need to talk again."
    ],
    //when nothing matches
    "(.*)": [
        "I'm not sure I understand. Can you elaborate?"
    ]
};

//https://www.w3schools.com/js/js_htmldom_eventlistener.asp
document.getElementById("sendBtn").addEventListener("click", communicate);

// Handle Message / send response
function communicate() {

    // recieve the message
    let message = document.getElementById("userInput").value;
    console.log(message);

    // wipe the input field
    document.getElementById("userInput").value = "";

    // add user message to the chat GUI
    // how to add a class in javascript
    // https://www.w3schools.com/howto/howto_js_add_class.asp
    let userMessageBox = document.createElement("div");
    userMessageBox.classList.add("message.user");
    userMessageBox.innerHTML = message;

    // respond with eliza logic 
    let response = respond(message);
    console.log("response: " + response);
    
    // add bot message to the chat GUI
    // how to add a class in javascript
    // https://www.w3schools.com/howto/howto_js_add_class.asp
    let botMessageBox = document.createElement("div");
    botMessageBox.classList.add("message.bot");
    botMessageBox.innerHTML = response;
}

// Function to reflect responses.
function reflect(text) {
    return text
        .split(" ")
        .map(word => reflections[word.toLowerCase()] || word)
        .join(" ");
}

// Function to select a suitable response based on the user's input.
function respond(userInput) {
    // loop over responses and extract the regex and associated response values
    for (const [pattern, responsesList] of Object.entries(responses)) {
        const regex = new RegExp(pattern, "i");
        const match = userInput.match(regex);

        if (match) {
            // Select a random response from the list.
            let response = responsesList[Math.floor(Math.random() * responsesList.length)];

            // Replace captured groups in the response, reflecting as needed.
            for (let i = 1; i < match.length; i++) {
                response = response.replace(`$${i}`, reflect(match[i]));
            }

            return response;
        }
    }

    // Default response if no patterns match.
    return "I'm not sure I understand. Can you elaborate?";
}